name: ChrisTESTER
favicon: null
layout_spectrum: 0.6772952757310122
typography_spectrum: 0.84161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2efea'
    - '#251909'
    - '#876810'
    - '#dacf3b'
    - '#921013'
  brandStrength: 0.7434055530466139
  lightness: 0.570522683672607
  saturation: 0.5154044926166534
  rhythmicContrast: 0.7489633774384856
purpose: []
